### ISSUE TITLE
StopIteration when doing --sort virtual on small filesystem

### ISSUE THREAD

**Issue by knorrie** [knorrie/btrfs-heatmap#4]
I'm writing tutorial documentation for python-btrfs and have a small 18GiB filesystem consisting of three 6GiB loop devices on top of files in another filesystem.

```
-# ./heatmap.py --sort virtual --size 8 /mnt/tutorial
scope chunks
grid curve hilbert order 5 size 8 height 32 width 32 total_bytes 19327352832 bytes_per_pixel 18874368.0
Traceback (most recent call last):
  File "./heatmap.py", line 632, in <module>
    main()
  File "./heatmap.py", line 605, in main
    curve=args.curve)
  File "./heatmap.py", line 377, in walk_chunks
    dev_extent_colors[block_group.flags & btrfs.BLOCK_GROUP_TYPE_MASK])
  File "./heatmap.py", line 318, in fill
    self._next_pixel()
  File "./heatmap.py", line 239, in _next_pixel
    self.y, self.x, self.linear = next(self.curve)
StopIteration
```

Boom! That shouldn't happen!

**Comment by knorrie** [comment]
Ah, duh...

```
-# ./show_usage.py /mnt/tutorial
dev item devid 1 total bytes 6442450944 bytes used 3026583552
dev item devid 2 total bytes 6442450944 bytes used 1961230336
dev item devid 3 total bytes 6442450944 bytes used 3034972160
block group vaddr 20971520 length 8388608 flags SYSTEM|RAID1 used 16384 used_pct 0
    chunk vaddr 20971520 type SYSTEM|RAID1 length 8388608 num_stripes 2
        stripe devid 3 offset 1048576
        stripe devid 2 offset 1048576
block group vaddr 29360128 length 1073741824 flags METADATA|RAID1 used 140083200 used_pct 13
    chunk vaddr 29360128 type METADATA|RAID1 length 1073741824 num_stripes 2
        stripe devid 1 offset 20971520
        stripe devid 3 offset 9437184
block group vaddr 1103101952 length 1932656640 flags DATA|RAID0 used 1932591104 used_pct 100
    chunk vaddr 1103101952 type DATA|RAID0 length 1932656640 num_stripes 3
        stripe devid 2 offset 9437184
        stripe devid 1 offset 1094713344
        stripe devid 3 offset 1083179008
block group vaddr 3035758592 length 1962934272 flags DATA|RAID0 used 1962934272 used_pct 100
    chunk vaddr 3035758592 type DATA|RAID0 length 1962934272 num_stripes 3
        stripe devid 2 offset 653656064
        stripe devid 1 offset 1738932224
        stripe devid 3 offset 1727397888
block group vaddr 4998692864 length 1962934272 flags DATA|RAID0 used 955039744 used_pct 49
    chunk vaddr 4998692864 type DATA|RAID0 length 1962934272 num_stripes 3
        stripe devid 2 offset 1307967488
        stripe devid 1 offset 2393243648
        stripe devid 3 offset 2381709312
```

And I'm doing (line 370):

```
length = chunk.length * len(stripes)
```

That of course is the wrong thing to do for a `RAID0` chunk. Instead, I need to have a look at the device extent objects for these stripe, and take the sum of their length.

**Comment by knorrie** [comment]
Euh, no.  Looking up device extents objects for each stripe would be a large waste of cpu and disk io. When the amount of stripe items in the chunk is known and the profile, we can calcute the actual total usage on disk with a few simple rules.

**Comment by knorrie** [comment]
* heatmap a48a494f1086289bbd7fb825af02e8d95255e317 "Fix raw disk space usage for chunks"
* python-btrfs  knorrie/python-btrfs@63769624f008e3c234c3e71fb94d6ea4aec5c467 "Add helper to calc dev extent length for chunk"

(commit ids might change because I tend to force-push in the development branch)

So, next btrfs-heatmap will depend on the next python-btrfs version.

**Comment by knorrie** [comment]
Ok, this is done. Just tagged v8 (which needs python-btrfs v10 for --sort virtual) and now it produces correct pictures and does not crash any more.
